name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Coverage
      run: yarn test --coverage
    - name: Add Coverage Badge
      uses: jpb06/jest-badges-action@v1.9.14

