name: CI
on: push

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Coverage
      run: yarn test --coverage --coverageReporters="json-summary,lcov"
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
         output-folder: './coverage/lcov-report/badges'
    - name: Publish test coverage report
      uses: EndBug/add-and-commit@v4
      with:
        add: './coverage/lcov-report'
        force: true
        message: Add code coverage report
    - name: Run Build
      run: yarn build
      
